M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-07-11T21:41:52+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-11T21:41:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
%
G90
G05
T1
X134.8Y-104.6
X142.8Y-104.6
M30
